displayName=Skill Rank Tooltip
author=YonwiPlugins
description=Shows your Old School RuneScape hiscore rank in skill tooltips
tags=skills,rank,hiscore,tooltip
version=
plugins=com.yonwiplugins.skillranktooltip.SkillRankTooltipPlugin
build=standard
