displayName=Skill Ranks
author=YonwiPlugins
description=Shows hiscore ranks in skill tooltips
tags=skills,rank,hiscore,tooltip
version=
plugins=com.yonwiplugins.skillranktooltip.SkillRankTooltipPlugin
build=standard
